### ISSUE TITLE
MIT License Violation

### ISSUE THREAD

**Issue by abalabahaha** [denosaurs/opus#1]
Hi there,

It looks like this repo violates the MIT License of [`opusscript`](https://github.com/abalabahaha/opusscript). Significant portions of the code in this repository seem to be copied from `opusscript` (of course with modifications for Deno), but the terms of the MIT License do not appear to have been followed. The MIT License states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This repo does appear to be using the MIT License, but it does not retain the copyright notice from `opusscript`, and the README does not give any indication of being any more than "related" to `opusscript`.

**Comment by eliassjogreen** [comment]
I'm sorry that we did that and it isn't our intention, I have updated the project with the original licence and changed our readme.

**Comment by abalabahaha** [comment]
No worries, thank you for understanding and correcting!
